---
rclone_arch: "arm64"
rclone_version: ""

# Remote server and volumes to mount.
cifs_server: my.smb.server
cifs_volumes:
  - "Media"
  - "Another Volume"
  - "Yet Another"

# SMB credentials.
cifs_username: backup
cifs_password: ""

# Other setup vars.
gickup_version: "0.10.26"
